### ISSUE TITLE
Doesn't work on Xcode 10.2.1 using Swift 4.2

### ISSUE THREAD

**Issue by d4rkd3v1l** [GDXRepo/CallStackParser#2]
At first I want to say that I really like the idea to have somewhat more readable and therefore usable stack traces.

Unfortunately it didn't work at all on my machine/project.
- first there is no `regexReplace` function in String (is this another extension, you forgot to include?)
- after using Swifts regex stuff here, I just got `nil`s from any function I called from this library.

Sorry, but atm I don't have any time for further investigation/debugging/fixing -.-

**Comment by GDXRepo** [comment]
This repo is outdated, so Swift APIs changing leads to the issue you mentioned.
